sudo: required 
services:
  - docker

before_install
  - docker build -t irfanromadona/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true irfanromadona/react-test npm test

after_success:
- docker build -t irfanromadona/multi-client -f ./client
- docker build -t irfanromadona/multi-nginx -f ./nginx
- docker build -t irfanromadona/multi-server -f ./server
- docker build -t irfanromadona/multi-worker -f ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push irfanromadona/multi-client 
- docker push irfanromadona/multi-nginx
- docker push irfanromadona/multi-server
- docker push irfanromadona/multi-worker
